"""Phase B3.1 shared-memory domain foundations (no SQLite / runtime enablement)."""

from __future__ import annotations

from .config import DEFAULT_MEMORY_CONFIG, MemoryConfig
from .domain import (
    CLASS_STATUS_PAIRINGS,
    ApprovalMethod,
    EvidenceStrength,
    LifecycleStatus,
    LinkType,
    MemoryAction,
    MemoryActorRole,
    MemoryCategory,
    MemoryClass,
    MemoryEvidenceRef,
    MemoryEvidenceType,
    MemoryLink,
    MemoryRecord,
    MemorySourceType,
    Sensitivity,
    is_valid_memory_evidence_id,
    is_valid_memory_event_id,
    is_valid_memory_id,
    is_valid_memory_link_id,
    new_memory_evidence_id,
    new_memory_event_id,
    new_memory_id,
    new_memory_link_id,
)
from .errors import (
    MemoryAuthorizationError,
    MemoryConflictError,
    MemoryDisabledError,
    MemoryError,
    MemoryIsolationError,
    MemoryNotFoundError,
    MemorySecurityError,
    MemoryValidationError,
)
from .hashing import (
    build_memory_fingerprint_payload,
    compute_content_hash,
    fingerprint_payload_from_record,
    memory_canonical_json,
    memory_sha256_hex,
)
from .normalization import normalize_memory_content, refuse_secrets_in_text
from .validation import (
    ACTION_ALLOWED_ROLES,
    LIFECYCLE_TRANSITIONS,
    authorize_memory_action,
    prepare_candidate_record,
    validate_class_status_pairing,
    validate_content_hash,
    validate_lifecycle_transition,
    validate_memory_record_fields,
    validate_propose_dict,
    validate_sensitivity_for_persist,
)
from .versions import (
    MEMORY_FINGERPRINT_VERSION,
    MEMORY_NORMALIZATION_VERSION,
    MEMORY_POLICY_VERSION,
    MEMORY_SCHEMA_VERSION,
)

__all__ = [
    "ACTION_ALLOWED_ROLES",
    "ApprovalMethod",
    "CLASS_STATUS_PAIRINGS",
    "DEFAULT_MEMORY_CONFIG",
    "EvidenceStrength",
    "LIFECYCLE_TRANSITIONS",
    "LifecycleStatus",
    "LinkType",
    "MEMORY_FINGERPRINT_VERSION",
    "MEMORY_NORMALIZATION_VERSION",
    "MEMORY_POLICY_VERSION",
    "MEMORY_SCHEMA_VERSION",
    "MemoryAction",
    "MemoryActorRole",
    "MemoryAuthorizationError",
    "MemoryCategory",
    "MemoryClass",
    "MemoryConfig",
    "MemoryConflictError",
    "MemoryDisabledError",
    "MemoryError",
    "MemoryEvidenceRef",
    "MemoryEvidenceType",
    "MemoryIsolationError",
    "MemoryLink",
    "MemoryNotFoundError",
    "MemoryRecord",
    "MemorySecurityError",
    "MemorySourceType",
    "MemoryValidationError",
    "Sensitivity",
    "authorize_memory_action",
    "build_memory_fingerprint_payload",
    "compute_content_hash",
    "fingerprint_payload_from_record",
    "is_valid_memory_evidence_id",
    "is_valid_memory_event_id",
    "is_valid_memory_id",
    "is_valid_memory_link_id",
    "memory_canonical_json",
    "memory_sha256_hex",
    "new_memory_evidence_id",
    "new_memory_event_id",
    "new_memory_id",
    "new_memory_link_id",
    "normalize_memory_content",
    "prepare_candidate_record",
    "refuse_secrets_in_text",
    "validate_class_status_pairing",
    "validate_content_hash",
    "validate_lifecycle_transition",
    "validate_memory_record_fields",
    "validate_propose_dict",
    "validate_sensitivity_for_persist",
]
