"""Round 4D1 / 4D1.1 / 4D1.2 / 4D1.3 provider-readiness version constants."""

from __future__ import annotations

READINESS_SCHEMA_VERSION = "4d1.3"
READINESS_POLICY_VERSION = "4d1.3"
EXECUTABLE_TRUST_POLICY_VERSION = "4d1.1.1"
VERSION_COMPATIBILITY_POLICY_VERSION = "4d1.3"
AUTHENTICATION_PROBE_POLICY_VERSION = "4d1.3"
AUTHENTICATION_MODE_POLICY_VERSION = "4d1.3"
NONINTERACTIVE_CONTRACT_POLICY_VERSION = "4d1.3"
ROLE_ELIGIBILITY_POLICY_VERSION = "4d1.3"
HOST_SYSTEM_VERDICT_SCHEMA_VERSION = "4d1.3"
SAFE_RUNNER_POLICY_VERSION = "4d1.3"
CODEX_EVENT_NORMALIZATION_SCHEMA_VERSION = "4d1.3"
CODEX_ENV_SANITIZATION_POLICY_VERSION = "4d1.3"
CODEX_COMPATIBILITY_POLICY_VERSION = "4d1.3"
OPEN_SOURCE_ADOPTION_ROADMAP_VERSION = "1.0"

# Round 4D1.1 ambiguity / pinning / selection schemas (unchanged)
AMBIGUITY_RESOLUTION_SCHEMA_VERSION = "4d1.1.1"
EXECUTABLE_IDENTITY_POLICY_VERSION = "4d1.1.1"
LOGICAL_INSTALLATION_POLICY_VERSION = "4d1.1.1"
EXECUTABLE_PIN_SCHEMA_VERSION = "4d1.1.1"
OPERATOR_SELECTION_SCHEMA_VERSION = "4d1.1.1"

PROBE_TIMEOUT_DEFAULT = 5.0
PROBE_TIMEOUT_MAX = 15.0
PROBE_OUTPUT_LIMIT = 8192
WRAPPER_READ_LIMIT = 16384
HELP_SUMMARY_LIMIT = 4000
