"""Round 4D1 provider-readiness version constants."""

from __future__ import annotations

READINESS_SCHEMA_VERSION = "4d1.1"
READINESS_POLICY_VERSION = "4d1.1"
EXECUTABLE_TRUST_POLICY_VERSION = "4d1.1"
VERSION_COMPATIBILITY_POLICY_VERSION = "4d1.1"
AUTHENTICATION_PROBE_POLICY_VERSION = "4d1.1"
ROLE_ELIGIBILITY_POLICY_VERSION = "4d1.1"
SAFE_RUNNER_POLICY_VERSION = "4d1.1"

PROBE_TIMEOUT_DEFAULT = 5.0
PROBE_TIMEOUT_MAX = 15.0
PROBE_OUTPUT_LIMIT = 8192
